INSERT INTO PUBLISHER(NAME, CITY, BASE_DISCOUNT_PERCENTAGE, BULK_PURCHASE_QUANTITY, BULK_DISCOUNT_PERCENTAGE)
VALUES('De Gouden Druk', 'Antwerpen',3,500,12);

INSERT INTO PUBLISHER(NAME, CITY, BASE_DISCOUNT_PERCENTAGE, BULK_PURCHASE_QUANTITY, BULK_DISCOUNT_PERCENTAGE)
VALUES('De Twee Zwanen','Brussel',4,400,15);

INSERT INTO PUBLISHER(NAME, CITY, BASE_DISCOUNT_PERCENTAGE, BULK_PURCHASE_QUANTITY, BULK_DISCOUNT_PERCENTAGE)
VALUES('Vlaamse Letters','Gent',2.5,600,10);

INSERT INTO PUBLISHER(NAME, CITY, BASE_DISCOUNT_PERCENTAGE, BULK_PURCHASE_QUANTITY, BULK_DISCOUNT_PERCENTAGE)
VALUES('Noorderlicht','Mechelen',5,300,18);

INSERT INTO PUBLISHER(NAME, CITY, BASE_DISCOUNT_PERCENTAGE, BULK_PURCHASE_QUANTITY, BULK_DISCOUNT_PERCENTAGE)
VALUES('Boekengilde','Hasselt',3.5,700,11.5);