insert into BOOK (TITLE) values ('Oryx and Crake');
insert into BOOK (TITLE) values ('The year of the flood');
insert into BOOK (TITLE) values ('MaddAddam');
insert into BOOK (TITLE) values ('1Q84');
insert into BOOK (TITLE) values ('De opwindvogelkronieken');
insert into BOOK (TITLE) values ('Design Patterns');
insert into BOOK (TITLE) values ('Het verdriet van België');
insert into BOOK (TITLE) values ('De kapellekensbaan');
insert into BOOK (TITLE) values ('Kaas');
insert into BOOK (TITLE) values ('De leeuw van Vlaanderen');
insert into BOOK (TITLE) values ('Houtekiet');
insert into BOOK (TITLE) values ('Will');
insert into BOOK (TITLE) values ('Sprakeloos');
insert into BOOK (TITLE) values ('Vallen');
insert into BOOK (TITLE) values ('De helaasheid der dingen');
insert into BOOK (TITLE) values ('Knielen op een bed violen');
insert into BOOK (TITLE) values ('Max Havelaar');
insert into BOOK (TITLE) values ('Karakter');
insert into BOOK (TITLE) values ('De ontdekking van de hemel');
insert into BOOK (TITLE) values ('De donkere kamer van Damokles');
insert into BOOK (TITLE) values ('De avonden');
insert into BOOK (TITLE) values ('De engelenmaker');
insert into BOOK (TITLE) values ('Grand Hotel Europa');
insert into BOOK (TITLE) values ('Lampje');
insert into BOOK (TITLE) values ('Things Fall Apart');
insert into BOOK (TITLE) values ('Het smelt');
insert into BOOK (TITLE) values ('Vele hemels boven de zevende');
insert into BOOK (TITLE) values ('Kom hier dat ik u kus');
insert into BOOK (TITLE) values ('Duet met valse noten');
insert into BOOK (TITLE) values ('De engelenmaker deel twee');
insert into BOOK (TITLE) values ('Het vierkant van de wraak');
insert into BOOK (TITLE) values ('De Midasmoorden');
insert into BOOK (TITLE) values ('Kartonnen dozen');
insert into BOOK (TITLE) values ('Sprakeloos en stil');
insert into BOOK (TITLE) values ('Lijmen / Het been');
insert into BOOK (TITLE) values ('Villa des Roses');
insert into BOOK (TITLE) values ('Menuet');
insert into BOOK (TITLE) values ('De Oostakkerse gedichten');
insert into BOOK (TITLE) values ('Het jaar van de kreeft');
insert into BOOK (TITLE) values ('Godverdomse dagen op een godverdomse bol');
insert into BOOK (TITLE) values ('Mevrouw Verona daalt de heuvel af');
insert into BOOK (TITLE) values ('Taal zonder mij');
insert into BOOK (TITLE) values ('Gitte');
insert into BOOK (TITLE) values ('Bezette Stad');
insert into BOOK (TITLE) values ('Titaantjes');
insert into BOOK (TITLE) values ('De kleine Johannes');
insert into BOOK (TITLE) values ('Eline Vere');
insert into BOOK (TITLE) values ('Het Vlaamse Kookboek');
insert into BOOK (TITLE) values ('Moderne Software Architectuur');
insert into BOOK (TITLE) values ('Database Systeem Concepten');

insert into AUTHOR (NAME) values ('Margaret Atwood');
insert into AUTHOR (NAME) values ('Haruki Murakami');
insert into AUTHOR (NAME) values ('Erich Gamma');
insert into AUTHOR (NAME) values ('Richard Helm');
insert into AUTHOR (NAME) values ('Ralph Johnson');
insert into AUTHOR (NAME) values ('John Vlissides');
insert into AUTHOR (NAME) values ('Hugo Claus');
insert into AUTHOR (NAME) values ('Louis Paul Boon');
insert into AUTHOR (NAME) values ('Willem Elsschot');
insert into AUTHOR (NAME) values ('Hendrik Conscience');
insert into AUTHOR (NAME) values ('Gerard Walschap');
insert into AUTHOR (NAME) values ('Jeroen Olyslaegers');
insert into AUTHOR (NAME) values ('Tom Lanoye');
insert into AUTHOR (NAME) values ('Anne Provoost');
insert into AUTHOR (NAME) values ('Dimitri Verhulst');
insert into AUTHOR (NAME) values ('Jan Siebelink');
insert into AUTHOR (NAME) values ('Multatuli');
insert into AUTHOR (NAME) values ('F. Bordewijk');
insert into AUTHOR (NAME) values ('Harry Mulisch');
insert into AUTHOR (NAME) values ('W.F. Hermans');
insert into AUTHOR (NAME) values ('Gerard Reve');
insert into AUTHOR (NAME) values ('Stefan Brijs');
insert into AUTHOR (NAME) values ('Ilja Leonard Pfeijffer');
insert into AUTHOR (NAME) values ('Annet Schaap');
insert into AUTHOR (NAME) values ('Chinua Achebe');
insert into AUTHOR (NAME) values ('Lize Spit');
insert into AUTHOR (NAME) values ('Griet Op de Beeck');
insert into AUTHOR (NAME) values ('Bart Moeyaert');
insert into AUTHOR (NAME) values ('Pieter Aspe');
insert into AUTHOR (NAME) values ('Kristien Hemmerechts');
insert into AUTHOR (NAME) values ('Paul van Ostaijen');
insert into AUTHOR (NAME) values ('Nescio');
insert into AUTHOR (NAME) values ('Frederik van Eeden');
insert into AUTHOR (NAME) values ('Louis Couperus');
insert into AUTHOR (NAME) values ('Geert Van Hecke');
insert into AUTHOR (NAME) values ('Peter Goossens');
insert into AUTHOR (NAME) values ('Youssef El Kaouakibi');
insert into AUTHOR (NAME) values ('Jean-Pierre Claes');

insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Oryx and Crake', select id from AUTHOR where name = 'Margaret Atwood');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'The year of the flood', select id from AUTHOR where name = 'Margaret Atwood');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'MaddAddam', select id from AUTHOR where name = 'Margaret Atwood');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= '1Q84', select id from AUTHOR where name = 'Haruki Murakami');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De opwindvogelkronieken', select id from AUTHOR where name = 'Haruki Murakami');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Design Patterns', select id from AUTHOR where name = 'Erich Gamma');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Design Patterns', select id from AUTHOR where name = 'Richard Helm');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Design Patterns', select id from AUTHOR where name = 'Ralph Johnson');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Design Patterns', select id from AUTHOR where name = 'John Vlissides');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het verdriet van België', select id from AUTHOR where name = 'Hugo Claus');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De kapellekensbaan', select id from AUTHOR where name = 'Louis Paul Boon');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Kaas', select id from AUTHOR where name = 'Willem Elsschot');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De leeuw van Vlaanderen', select id from AUTHOR where name = 'Hendrik Conscience');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Houtekiet', select id from AUTHOR where name = 'Gerard Walschap');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Will', select id from AUTHOR where name = 'Jeroen Olyslaegers');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Sprakeloos', select id from AUTHOR where name = 'Tom Lanoye');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Vallen', select id from AUTHOR where name = 'Anne Provoost');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De helaasheid der dingen', select id from AUTHOR where name = 'Dimitri Verhulst');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Knielen op een bed violen', select id from AUTHOR where name = 'Jan Siebelink');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Max Havelaar', select id from AUTHOR where name = 'Multatuli');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Karakter', select id from AUTHOR where name = 'F. Bordewijk');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De ontdekking van de hemel', select id from AUTHOR where name = 'Harry Mulisch');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De donkere kamer van Damokles', select id from AUTHOR where name = 'W.F. Hermans');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De avonden', select id from AUTHOR where name = 'Gerard Reve');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De engelenmaker', select id from AUTHOR where name = 'Stefan Brijs');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Grand Hotel Europa', select id from AUTHOR where name = 'Ilja Leonard Pfeijffer');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Lampje', select id from AUTHOR where name = 'Annet Schaap');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Things Fall Apart', select id from AUTHOR where name = 'Chinua Achebe');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het smelt', select id from AUTHOR where name = 'Lize Spit');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Vele hemels boven de zevende', select id from AUTHOR where name = 'Griet Op de Beeck');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Kom hier dat ik u kus', select id from AUTHOR where name = 'Griet Op de Beeck');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Duet met valse noten', select id from AUTHOR where name = 'Bart Moeyaert');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De engelenmaker deel twee', select id from AUTHOR where name = 'Stefan Brijs');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het vierkant van de wraak', select id from AUTHOR where name = 'Pieter Aspe');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De Midasmoorden', select id from AUTHOR where name = 'Pieter Aspe');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Kartonnen dozen', select id from AUTHOR where name = 'Tom Lanoye');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Sprakeloos en stil', select id from AUTHOR where name = 'Tom Lanoye');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Lijmen / Het been', select id from AUTHOR where name = 'Willem Elsschot');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Villa des Roses', select id from AUTHOR where name = 'Willem Elsschot');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Menuet', select id from AUTHOR where name = 'Louis Paul Boon');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De Oostakkerse gedichten', select id from AUTHOR where name = 'Hugo Claus');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het jaar van de kreeft', select id from AUTHOR where name = 'Hugo Claus');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Godverdomse dagen op een godverdomse bol', select id from AUTHOR where name = 'Dimitri Verhulst');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Mevrouw Verona daalt de heuvel af', select id from AUTHOR where name = 'Dimitri Verhulst');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Taal zonder mij', select id from AUTHOR where name = 'Kristien Hemmerechts');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Gitte', select id from AUTHOR where name = 'Kristien Hemmerechts');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Bezette Stad', select id from AUTHOR where name = 'Paul van Ostaijen');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Titaantjes', select id from AUTHOR where name = 'Nescio');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De kleine Johannes', select id from AUTHOR where name = 'Frederik van Eeden');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Eline Vere', select id from AUTHOR where name = 'Louis Couperus');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het Vlaamse Kookboek', select id from AUTHOR where name = 'Geert Van Hecke');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het Vlaamse Kookboek', select id from AUTHOR where name = 'Peter Goossens');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Moderne Software Architectuur', select id from AUTHOR where name = 'Youssef El Kaouakibi');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Moderne Software Architectuur', select id from AUTHOR where name = 'Jean-Pierre Claes');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Database Systeem Concepten', select id from AUTHOR where name = 'Jean-Pierre Claes');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Database Systeem Concepten', select id from AUTHOR where name = 'Youssef El Kaouakibi');

insert into GENRE(NAME) values ('Fantasie');
insert into GENRE(NAME) values ('Non-fictie');
insert into GENRE(NAME) values ('Programmeren');
insert into GENRE(NAME) values ('Romans');
insert into GENRE(NAME) values ('Poëzie');
insert into GENRE(NAME) values ('Geschiedenis');
insert into GENRE(NAME) values ('Biografie');
insert into GENRE(NAME) values ('Jeugdliteratuur');
insert into GENRE(NAME) values ('Thriller');
insert into GENRE(NAME) values ('Wetenschap');

INSERT INTO users (username, password, enabled) VALUES ('admin', '$2a$10$9MIX8kYPkuB7uE/H5nHF8.KG6.YdjBA/voOnjSZnZDxLXL/2BIerS', true);
INSERT INTO authorities (username, authority) VALUES ('admin', 'ADMIN');

INSERT INTO users (username, password, enabled) VALUES ('marie', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('marie', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('vera', '$2y$12$KF3spKP4kgf59.6zYkmjyeYaW2.4ZxV16Grpw1FPsFnzYq68kswJ6', true);
INSERT INTO authorities (username, authority) VALUES ('vera', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('thomas', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('thomas', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('anke', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('anke', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('filip', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('filip', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('liesbeth', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('liesbeth', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('stefan', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('stefan', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('jan', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('jan', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('niels', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('niels', 'USER');

