insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Oryx and Crake', 2003, 'Een speculatieve fictie roman van Margaret Atwood.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('The year of the flood', 2009, 'Het tweede boek in de MaddAddam-trilogie.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('MaddAddam', 2013, 'Het spannende slotstuk van de trilogie.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('1Q84', 2009, 'Een dystopische roman geschreven door Haruki Murakami.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De opwindvogelkronieken', 1994, 'Een meesterwerk over de zoektocht naar een vermiste kat en echtgenote.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Design Patterns', 1994, 'Klassiek software engineering boek over herbruikbare ontwerppatronen.', 'Engels');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Het verdriet van België', 1983, 'De bekendste roman van Hugo Claus over de oorlogsjaren in Vlaanderen.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De kapellekensbaan', 1953, 'Sociaal-realistisch meesterwerk van Louis Paul Boon.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Kaas', 1933, 'Klassieke novelle over de kaasdroom van Frans Laarmans.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De leeuw van Vlaanderen', 1838, 'Historische roman over de Guldensporenslag.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Houtekiet', 1939, 'Roman van Gerard Walschap over de stichting van een nieuwe gemeenschap.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Will', 2016, 'Roman over collaboratie en overleven in Antwerpen tijdens WOII.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Sprakeloos', 2009, 'Persoonlijk en ontroerend eerbetoon van Tom Lanoye aan zijn moeder.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Vallen', 1994, 'Jeugdroman over radicalisering en verleiding door extreemrechts.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De helaasheid der dingen', 2006, 'Tragikomisch portret van een marginale jeugd in Reetveerdegem.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Knielen op een bed violen', 2005, 'Bestseller van Jan Siebelink over geloofswaan.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Max Havelaar', 1860, 'Klassieke aanklacht tegen het Nederlandse koloniale bewind.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Karakter', 1938, 'Roman over de strijd tussen vader Dreverhaven en zoon Katadreuffe.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De ontdekking van de hemel', 1992, 'Magnum opus van Harry Mulisch over vriendschap en lotsbestemming.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De donkere kamer van Damokles', 1958, 'Existentiële oorlogsroman over Henri Osewoudt.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De avonden', 1947, 'Klassieker over de naoorlogse beklemming van Frits van Egters.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De engelenmaker', 2005, 'Fascinerende roman over een arts die zijn eigen kinderen kloont.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Grand Hotel Europa', 2018, 'Roman over de Europese identiteit, nostalgie en toerisme.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Lampje', 2017, 'Bekroond jeugdboek over de dochter van de vuurtorenwachter.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Things Fall Apart', 1958, 'Invloedrijke Afrikaanse roman over de impact van het kolonialisme.', 'Engels');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Het smelt', 2015, 'Beklijvend en intens debuut van Lize Spit.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Vele hemels boven de zevende', 2013, 'Ontroerende mozaïekroman over vijf verschillende personages.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Kom hier dat ik u kus', 2014, 'Psychologische roman over opgroeien en familierelaties.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Duet met valse noten', 1983, 'Klassieke jeugdroman over een turbulente tienerliefde.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De engelenmaker deel twee', 2010, 'Fictief vervolg op de succesvolle roman van Stefan Brijs.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Het vierkant van de wraak', 1995, 'De eerste misdaadroman van Pieter Aspe met commissaris Van In.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De Midasmoorden', 1996, 'Spannende thriller van Pieter Aspe gesitueerd in Brugge.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Kartonnen dozen', 1991, 'Autobiografisch werk over de jeugdliefde van Tom Lanoye.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Sprakeloos en stil', 2012, 'Vervolg of gerelateerd werk aan de eerdere familieromans.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Lijmen / Het been', 1924, 'Beroemd tweeluik over reclamepraktijken en ethische dilemma''s.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Villa des Roses', 1913, 'Het debuut van Willem Elsschot over een Parijs pension.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Menuet', 1955, 'Modernistische novelle over de relatie tussen drie mensen.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De Oostakkerse gedichten', 1955, 'Grensverleggende dichtbundel van Hugo Claus.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Het jaar van de kreeft', 1972, 'Roman over een stormachtige en destructieve liefdesrelatie.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Godverdomse dagen op een godverdomse bol', 2008, 'Rauwe geschiedschrijving van de mensheid door Dimitri Verhulst.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Mevrouw Verona daalt de heuvel af', 2006, 'Poëtische en melancholische novelle over liefde en verlies.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Taal zonder mij', 1998, 'Persoonlijk essay en eerbetoon aan Herman de Coninck.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Gitte', 2005, 'Vlaamse literatuur over opgroeien en persoonlijke relaties.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Bezette Stad', 1921, 'Expressionistisch meesterwerk en dichtbundel over Antwerpen.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Titaantjes', 1915, 'Klassiek verhaal over idealistische vrienden die ouder worden.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('De kleine Johannes', 1887, 'Symbolisch sprookje over de weg naar volwassenheid.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Eline Vere', 1889, 'Haagse zedenroman en meesterwerk van het naturalisme.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Het Vlaamse Kookboek', 2002, 'Kookboek met klassieke recepten uit de Vlaamse gastronomie.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Moderne Software Architectuur', 2020, 'Praktische gids over microservices en cloud architectuur.', 'Nederlands');
insert into BOOK (TITLE, PUBLICATION_YEAR, DESCRIPTION, LANGUAGE) values ('Database Systeem Concepten', 2018, 'Handboek over relationele databases en SQL-technologie.', 'Nederlands');

insert into AUTHOR (NAME) values ('Margaret Atwood');
insert into AUTHOR (NAME) values ('Haruki Murakami');
insert into AUTHOR (NAME) values ('Erich Gamma');
insert into AUTHOR (NAME) values ('Richard Helm');
insert into AUTHOR (NAME) values ('Ralph Johnson');
insert into AUTHOR (NAME) values ('John Vlissides');
insert into AUTHOR (NAME) values ('Hugo Claus');
insert into AUTHOR (NAME) values ('Louis Paul Boon');
insert into AUTHOR (NAME) values ('Willem Elsschot');
insert into AUTHOR (NAME) values ('Hendrik Conscience');
insert into AUTHOR (NAME) values ('Gerard Walschap');
insert into AUTHOR (NAME) values ('Jeroen Olyslaegers');
insert into AUTHOR (NAME) values ('Tom Lanoye');
insert into AUTHOR (NAME) values ('Anne Provoost');
insert into AUTHOR (NAME) values ('Dimitri Verhulst');
insert into AUTHOR (NAME) values ('Jan Siebelink');
insert into AUTHOR (NAME) values ('Multatuli');
insert into AUTHOR (NAME) values ('F. Bordewijk');
insert into AUTHOR (NAME) values ('Harry Mulisch');
insert into AUTHOR (NAME) values ('W.F. Hermans');
insert into AUTHOR (NAME) values ('Gerard Reve');
insert into AUTHOR (NAME) values ('Stefan Brijs');
insert into AUTHOR (NAME) values ('Ilja Leonard Pfeijffer');
insert into AUTHOR (NAME) values ('Annet Schaap');
insert into AUTHOR (NAME) values ('Chinua Achebe');
insert into AUTHOR (NAME) values ('Lize Spit');
insert into AUTHOR (NAME) values ('Griet Op de Beeck');
insert into AUTHOR (NAME) values ('Bart Moeyaert');
insert into AUTHOR (NAME) values ('Pieter Aspe');
insert into AUTHOR (NAME) values ('Kristien Hemmerechts');
insert into AUTHOR (NAME) values ('Paul van Ostaijen');
insert into AUTHOR (NAME) values ('Nescio');
insert into AUTHOR (NAME) values ('Frederik van Eeden');
insert into AUTHOR (NAME) values ('Louis Couperus');
insert into AUTHOR (NAME) values ('Geert Van Hecke');
insert into AUTHOR (NAME) values ('Peter Goossens');
insert into AUTHOR (NAME) values ('Youssef El Kaouakibi');
insert into AUTHOR (NAME) values ('Jean-Pierre Claes');

insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Oryx and Crake', select id from AUTHOR where name = 'Margaret Atwood');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'The year of the flood', select id from AUTHOR where name = 'Margaret Atwood');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'MaddAddam', select id from AUTHOR where name = 'Margaret Atwood');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= '1Q84', select id from AUTHOR where name = 'Haruki Murakami');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De opwindvogelkronieken', select id from AUTHOR where name = 'Haruki Murakami');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Design Patterns', select id from AUTHOR where name = 'Erich Gamma');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Design Patterns', select id from AUTHOR where name = 'Richard Helm');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Design Patterns', select id from AUTHOR where name = 'Ralph Johnson');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Design Patterns', select id from AUTHOR where name = 'John Vlissides');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het verdriet van België', select id from AUTHOR where name = 'Hugo Claus');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De kapellekensbaan', select id from AUTHOR where name = 'Louis Paul Boon');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Kaas', select id from AUTHOR where name = 'Willem Elsschot');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De leeuw van Vlaanderen', select id from AUTHOR where name = 'Hendrik Conscience');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Houtekiet', select id from AUTHOR where name = 'Gerard Walschap');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Will', select id from AUTHOR where name = 'Jeroen Olyslaegers');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Sprakeloos', select id from AUTHOR where name = 'Tom Lanoye');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Vallen', select id from AUTHOR where name = 'Anne Provoost');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De helaasheid der dingen', select id from AUTHOR where name = 'Dimitri Verhulst');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Knielen op een bed violen', select id from AUTHOR where name = 'Jan Siebelink');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Max Havelaar', select id from AUTHOR where name = 'Multatuli');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Karakter', select id from AUTHOR where name = 'F. Bordewijk');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De ontdekking van de hemel', select id from AUTHOR where name = 'Harry Mulisch');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De donkere kamer van Damokles', select id from AUTHOR where name = 'W.F. Hermans');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De avonden', select id from AUTHOR where name = 'Gerard Reve');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De engelenmaker', select id from AUTHOR where name = 'Stefan Brijs');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Grand Hotel Europa', select id from AUTHOR where name = 'Ilja Leonard Pfeijffer');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Lampje', select id from AUTHOR where name = 'Annet Schaap');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Things Fall Apart', select id from AUTHOR where name = 'Chinua Achebe');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het smelt', select id from AUTHOR where name = 'Lize Spit');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Vele hemels boven de zevende', select id from AUTHOR where name = 'Griet Op de Beeck');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Kom hier dat ik u kus', select id from AUTHOR where name = 'Griet Op de Beeck');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Duet met valse noten', select id from AUTHOR where name = 'Bart Moeyaert');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De engelenmaker deel twee', select id from AUTHOR where name = 'Stefan Brijs');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het vierkant van de wraak', select id from AUTHOR where name = 'Pieter Aspe');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De Midasmoorden', select id from AUTHOR where name = 'Pieter Aspe');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Kartonnen dozen', select id from AUTHOR where name = 'Tom Lanoye');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Sprakeloos en stil', select id from AUTHOR where name = 'Tom Lanoye');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Lijmen / Het been', select id from AUTHOR where name = 'Willem Elsschot');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Villa des Roses', select id from AUTHOR where name = 'Willem Elsschot');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Menuet', select id from AUTHOR where name = 'Louis Paul Boon');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De Oostakkerse gedichten', select id from AUTHOR where name = 'Hugo Claus');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het jaar van de kreeft', select id from AUTHOR where name = 'Hugo Claus');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Godverdomse dagen op een godverdomse bol', select id from AUTHOR where name = 'Dimitri Verhulst');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Mevrouw Verona daalt de heuvel af', select id from AUTHOR where name = 'Dimitri Verhulst');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Taal zonder mij', select id from AUTHOR where name = 'Kristien Hemmerechts');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Gitte', select id from AUTHOR where name = 'Kristien Hemmerechts');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Bezette Stad', select id from AUTHOR where name = 'Paul van Ostaijen');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Titaantjes', select id from AUTHOR where name = 'Nescio');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'De kleine Johannes', select id from AUTHOR where name = 'Frederik van Eeden');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Eline Vere', select id from AUTHOR where name = 'Louis Couperus');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het Vlaamse Kookboek', select id from AUTHOR where name = 'Geert Van Hecke');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Het Vlaamse Kookboek', select id from AUTHOR where name = 'Peter Goossens');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Moderne Software Architectuur', select id from AUTHOR where name = 'Youssef El Kaouakibi');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Moderne Software Architectuur', select id from AUTHOR where name = 'Jean-Pierre Claes');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Database Systeem Concepten', select id from AUTHOR where name = 'Jean-Pierre Claes');
insert into BOOK_AUTHORS (BOOKS_ID, AUTHORS_ID) values (select id from BOOK where title= 'Database Systeem Concepten', select id from AUTHOR where name = 'Youssef El Kaouakibi');

insert into GENRE(NAME) values ('Fantasie');
insert into GENRE(NAME) values ('Non-fictie');
insert into GENRE(NAME) values ('Programmeren');
insert into GENRE(NAME) values ('Romans');
insert into GENRE(NAME) values ('Poëzie');
insert into GENRE(NAME) values ('Geschiedenis');
insert into GENRE(NAME) values ('Biografie');
insert into GENRE(NAME) values ('Jeugdliteratuur');
insert into GENRE(NAME) values ('Thriller');
insert into GENRE(NAME) values ('Wetenschap');

INSERT INTO users (username, password, enabled) VALUES ('admin', '$2a$10$9MIX8kYPkuB7uE/H5nHF8.KG6.YdjBA/voOnjSZnZDxLXL/2BIerS', true);
INSERT INTO authorities (username, authority) VALUES ('admin', 'ADMIN');

INSERT INTO users (username, password, enabled) VALUES ('marie', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('marie', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('vera', '$2y$12$KF3spKP4kgf59.6zYkmjyeYaW2.4ZxV16Grpw1FPsFnzYq68kswJ6', true);
INSERT INTO authorities (username, authority) VALUES ('vera', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('thomas', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('thomas', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('anke', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('anke', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('filip', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('filip', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('liesbeth', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('liesbeth', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('stefan', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('stefan', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('jan', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('jan', 'USER');

INSERT INTO users (username, password, enabled) VALUES ('niels', '$2a$10$9TeBFudS7HsgCa4sSvP//O627sMq.KiTFrOr8IzrVlYw5c8aoKzNm', true);
INSERT INTO authorities (username, authority) VALUES ('niels', 'USER');

INSERT INTO member (username, email) VALUES ('admin', 'admin@thomasmore.be');
INSERT INTO member (username, email) VALUES ('marie', 'marie@thomasmore.be');
INSERT INTO member (username, email) VALUES ('vera', 'vera@thomasmore.be');
INSERT INTO member (username, email) VALUES ('thomas', 'thomas@thomasmore.be');
INSERT INTO member (username, email) VALUES ('anke', 'anke@thomasmore.be');
INSERT INTO member (username, email) VALUES ('filip', 'filip@thomasmore.be');
INSERT INTO member (username, email) VALUES ('liesbeth', 'liesbeth@thomasmore.be');
INSERT INTO member (username, email) VALUES ('stefan', 'stefan@thomasmore.be');
INSERT INTO member (username, email) VALUES ('jan', 'jan@thomasmore.be');
INSERT INTO member (username, email) VALUES ('niels', 'niels@thomasmore.be');


